"""Owned UI seams. The upstream renderer, suggestions and input actions remain intact."""
def apply(main, replace):
    base = main / "java/helium314/keyboard"
    replace(base / 'latin/suggestions/SuggestionStripView.kt', '    init {\n        val colors = Settings.getValues().mColors\n\n        // expand key\n        // weird way of setting size (default is config_suggestions_strip_edge_key_width)\n        // but better not change it or people will complain\n        val toolbarHeight = min(toolbarExpandKey.layoutParams.height, resources.getDimension(R.dimen.config_suggestions_strip_height).toInt())\n        toolbarExpandKey.layoutParams.height = toolbarHeight\n        toolbarExpandKey.layoutParams.width = toolbarHeight // we want it square\n        colors.setBackground(toolbarExpandKey, ColorType.STRIP_BACKGROUND) // necessary because background is re-used for defaultToolbarBackground\n        colors.setColor(toolbarExpandKey, ColorType.TOOL_BAR_EXPAND_KEY)\n        colors.setColor(toolbarExpandKey.background, ColorType.TOOL_BAR_EXPAND_KEY_BACKGROUND)\n\n        // background indicator for pinned keys\n        val color = colors.get(ColorType.TOOL_BAR_KEY_ENABLED_BACKGROUND) or -0x1000000 // ignore alpha (in Java this is more readable 0xFF000000)\n        enabledToolKeyBackground.colors = intArrayOf(color, Color.TRANSPARENT)\n        enabledToolKeyBackground.gradientType = GradientDrawable.RADIAL_GRADIENT\n        enabledToolKeyBackground.gradientRadius = resources.getDimensionPixelSize(R.dimen.config_suggestions_strip_height) / 2.1f\n\n        val mToolbarMode = if (isGone) ToolbarMode.HIDDEN else Settings.getValues().mToolbarMode\n        if (mToolbarMode == ToolbarMode.TOOLBAR_KEYS) {\n            setToolbarVisibility(true)\n        }\n\n        // toolbar keys setup (no need to hide them any more when locked, because then suggestion strip is gone anyway\n        for (key in getEnabledToolbarKeys(context.prefs())) {\n            val button = createToolbarKey(context, key)\n            button.layoutParams = toolbarKeyLayoutParams\n            setupKey(button, colors)\n            toolbar.addView(button)\n        }\n        for (pinnedKey in getPinnedToolbarKeys(context.prefs())) {\n            val button = createToolbarKey(context, pinnedKey)\n            button.layoutParams = toolbarKeyLayoutParams\n            setupKey(button, colors)\n            pinnedKeys.addView(button)\n            val pinnedKeyInToolbar = toolbar.findViewWithTag<View>(pinnedKey)\n            if (pinnedKeyInToolbar != null && Settings.getValues().mQuickPinToolbarKeys)\n                pinnedKeyInToolbar.background = enabledToolKeyBackground\n        }\n        toolbarContainer.doOnNextLayout {\n            // set min with of the toolbar so the weight of the toolbar keys actually does something\n            // todo: results in requestLayout() improperly called by android.widget.LinearLayout during layout: running second layout pass\n            toolbar.minimumWidth = toolbarContainer.width\n        }\n\n        updateKeys()\n    }\n\n', '    // ObadhToolbar owns the fixed controls.\n\n')
    replace(base / 'latin/suggestions/SuggestionStripView.kt', '    // public stuff', '    private val obadhToolbar = helium314.keyboard.latin.obadh.ObadhToolbar(this) { code ->\n        listener.onCodeInput(code, Constants.SUGGESTION_STRIP_COORDINATE, Constants.SUGGESTION_STRIP_COORDINATE, false)\n    }\n\n    // public stuff')
    replace(base / 'latin/suggestions/SuggestionStripView.kt', '    fun setToolbarVisibility(toolbarVisible: Boolean) {\n        pinnedKeys.isVisible = !toolbarVisible\n        suggestionsStrip.isVisible = !toolbarVisible\n        toolbarContainer.isVisible = toolbarVisible\n\n        if (DEBUG_SUGGESTIONS) {\n            for (view in debugInfoViews) {\n                view.visibility = suggestionsStrip.visibility\n            }\n        }\n\n        toolbarExpandKey.scaleX = (if (toolbarVisible) -1f else 1f) * direction\n    }\n\n', '    fun setToolbarVisibility(toolbarVisible: Boolean) {\n        obadhToolbar.update(suggestedWords, isExternalSuggestionVisible)\n    }\n\n')
    replace(base / 'latin/suggestions/SuggestionStripView.kt', '    fun updateVoiceKey() {\n        val show = Settings.getValues().mShowsVoiceInputKey\n        toolbar.findViewWithTag<View>(ToolbarKey.VOICE)?.isVisible = show\n        pinnedKeys.findViewWithTag<View>(ToolbarKey.VOICE)?.isVisible = show\n    }\n\n    private fun updateKeys() {\n        updateVoiceKey()\n        val settingsValues = Settings.getValues()\n\n        val toolbarIsExpandable = settingsValues.mToolbarMode == ToolbarMode.EXPANDABLE\n        if (settingsValues.mIncognitoModeEnabled) {\n            toolbarExpandKey.setImageDrawable(incognitoIcon)\n            toolbarExpandKey.isVisible = true\n        } else {\n            toolbarExpandKey.setImageDrawable(toolbarArrowIcon)\n            toolbarExpandKey.isVisible = toolbarIsExpandable\n        }\n\n        toolbarExpandKey.setOnClickListener(if (!toolbarIsExpandable) null else this)\n        pinnedKeys.visibility = suggestionsStrip.visibility\n        isExternalSuggestionVisible = false\n    }\n\n', '    fun updateVoiceKey() {} // The microphone is an owned, permission-free release placeholder.\n\n    private fun updateKeys() {\n        obadhToolbar.update(suggestedWords, isExternalSuggestionVisible)\n    }\n\n')
    replace(base / 'latin/suggestions/SuggestionStripView.kt', '        dismissMoreSuggestionsPanel()\n    }\n\n    override fun onSizeChanged', '        dismissMoreSuggestionsPanel()\n        obadhToolbar.close()\n    }\n\n    override fun onSizeChanged')
    replace(base / 'keyboard/internal/KeyboardIconsSet.kt', '        val ids = if (overrideIds.isEmpty()) defaultIds else defaultIds + overrideIds', '        val ids = defaultIds + mapOf(\n            "emoji" to R.drawable.obadh_ic_sentiment_satisfied,\n            "clipboard" to R.drawable.obadh_ic_assignment,\n            "settings" to R.drawable.obadh_ic_settings,\n            "voice" to R.drawable.obadh_ic_mic,\n            NAME_LANGUAGE_SWITCH_KEY to R.drawable.obadh_ic_language,\n            NAME_DELETE_KEY to R.drawable.obadh_ic_backspace,\n            NAME_ENTER_KEY to R.drawable.obadh_ic_keyboard_return,\n            NAME_GO_KEY to R.drawable.obadh_ic_arrow_forward,\n            NAME_NEXT_KEY to R.drawable.obadh_ic_arrow_forward,\n            NAME_SEARCH_KEY to R.drawable.obadh_ic_search,\n            NAME_SEND_KEY to R.drawable.obadh_ic_send,\n        ) + overrideIds')
    replace(base / 'keyboard/internal/keyboard_parser/floris/TextKeyData.kt', '        private fun getCommaPopupKeys(params: KeyboardParams): List<String> {', '        private fun getCommaPopupKeys(params: KeyboardParams): List<String> {\n            if (params.mId.element.isAlphabet && !params.mId.isPasswordInput)\n                return listOf("!noPanelAutoPopupKey!", "!icon/emoji_normal_key|!code/key_emoji")')
    replace(base / 'latin/utils/PopupKeysUtils.kt', 'private fun getHintText(popupSet: PopupSet<*>?, params: KeyboardParams, label: String): String? {', 'private fun getHintText(popupSet: PopupSet<*>?, params: KeyboardParams, label: String): String? {\n    if (params.mId.element.isAlphabet && label.length == 1 && label.lowercase()[0] in \'a\'..\'z\') {\n        val index = "qwertyuiop".indexOf(label.lowercase())\n        if (index >= 0) return "1234567890"[index].toString()\n        if (!helium314.keyboard.latin.settings.Settings.getValues().mObadhSecondaryHints) return null\n    }')
    replace(base / 'keyboard/KeyboardView.java', '        // Draw key label.\n        final Keyboard keyboard = getKeyboard();', '        // Draw key label.\n        final Keyboard keyboard = getKeyboard();\n        if (keyboard != null && keyboard.mId.getElement().isAlphabet() && key.getCode() == 44\n                && !keyboard.mId.isPasswordInput()) {\n            helium314.keyboard.latin.obadh.ObadhKeyVisuals.drawComma(key, canvas, paint, params, keyboard, getResources().getDisplayMetrics().density);\n            return;\n        }')
    replace(base / "latin/settings/SettingsValues.java", "    public final InputAttributes mInputAttributes;", "    public final InputAttributes mInputAttributes;\n    public final boolean mObadhSecondaryHints;")
    replace(base / "latin/settings/SettingsValues.java", "        mInputAttributes = inputAttributes;", "        mInputAttributes = inputAttributes;\n        mObadhSecondaryHints = prefs.getBoolean(\"obadh.secondary_hints\", false);")
    replace(base / "keyboard/KeyboardView.java", "                mColors.setColor(icon, ColorType.KEY_ICON); // normal key if not shifted", "                mColors.setColor(icon, ColorType.FUNCTIONAL_KEY_TEXT); // matches functional key foreground")
    replace(base / "keyboard/KeyboardView.java", "        } else if (key.getBackgroundType() != Key.BACKGROUND_TYPE_NORMAL) {\n            mColors.setColor(icon, ColorType.KEY_ICON);", "        } else if (key.getBackgroundType() != Key.BACKGROUND_TYPE_NORMAL) {\n            mColors.setColor(icon, key.hasFunctionalBackground() ? ColorType.FUNCTIONAL_KEY_TEXT : ColorType.KEY_ICON);")
    replace(base / "latin/suggestions/SuggestionStripView.kt", "        setToolbarButtonsActivatedStateOnPrefChange(pinnedKeys, key)\n        setToolbarButtonsActivatedStateOnPrefChange(toolbar, key)", "        // Fixed toolbar buttons do not use upstream pin/activation mutation.\n        // Candidate and external-suggestion state stays on the main thread.")

    replace(base / "latin/suggestions/SuggestionStripView.kt", "    override fun onSizeChanged", "    override fun onWindowVisibilityChanged(visibility: Int) {\n        super.onWindowVisibilityChanged(visibility)\n        if (visibility != android.view.View.VISIBLE) obadhToolbar.close()\n    }\n\n    override fun onSizeChanged")

    replace(base / "latin/suggestions/SuggestionStripView.kt", "            toolbarExpandKey.scaleX = (if (toolbarContainer.visibility != VISIBLE) 1f else -1f) * direction", "            toolbarExpandKey.scaleX = 1f // The fixed grid/back control is not an expansion arrow.")

    replace(base / "latin/suggestions/SuggestionStripView.kt", "    fun updateVoiceKey() {}", "    fun obadhToolbarCoordinatesForTests() = obadhToolbar.coordinatesForTests()\n\n    fun updateVoiceKey() {}")
